language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

addons:
  code_climate:
    repo_token: 23d690c097ec03837ec5e823c7c6b3dcda75524be03a3b067698e09154b3aeef
    
    install:
  - npm install -g codecov
script:
  - istanbul cover node_modules\jasmine\bin\jasmine.js
  - codecov
