language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
  
script: npm start

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: feature_branch
  local_dir: "output"
